language: cpp
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - Coverage=ON BuildType=Release Implementation=Compact
  - Coverage=ON BuildType=Release Implementation=Optimised
matrix:
  allow_failures:
    - env: Coverage=ON BuildType=Release Implementation=SIMD

install:
  # Installing CMake 3.2.1
  - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -xzf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1
  - cmake . > /dev/null
  - make > /dev/null
  - cd ..
  - rm -rf cmake-3.2.1.tar.gz

before_script:
  - cmake-3.2.1/bin/cmake --version
  - mkdir build
  - cd build
  
  - ../cmake-3.2.1/bin/cmake
    -DCMAKE_BUILD_TYPE=$BuildType
    -DIMPLEMENTATION=$Implementation
    -DENABLE_COVERAGE=$Coverage
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE_RULE_MESSAGES=OFF
    ../src/

script:
  - make --no-print-directory all
  - cd libgost15/tests/ && ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)
