language: c
os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

env:
matrix:
  - BUILD_TYPE=Release
#  - BUILD_TYPE=Debug
  - ENABLE_PRECALCULATIONS=OFF                    # compact version
#  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=OFF     # optimised version
#  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=ON      # SIMD version

install:
  # Installing CMake 3.2.1
  - sudo apt-get remove cmake
  - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -xzf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1
  - ./bootstrap > /dev/null
  - make -j8 > /dev/null
  - sudo make install
  - cd ..
  - rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz

before_script:
  - cmake --version
  - mkdir build
  - cd build

script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ../src
    - make selftests_gost
    - ./libgost15/tests/selftests_gost