language:
  C++
sudo:
  false
addons:
  apt:
    packages:
    - cmake

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
matrix:
  - ENABLE_PRECALCULATIONS=OFF ENABLE_SIMD=OFF BUILD_TYPE=Release
  - ENABLE_PRECALCULATIONS=OFF ENABLE_SIMD=OFF BUILD_TYPE=Debug
  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=OFF BUILD_TYPE=Release
  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=OFF BUILD_TYPE=Debug
allow_failures:
  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=ON BUILD_TYPE=Release
  - ENABLE_PRECALCULATIONS=ON ENABLE_SIMD=ON BUILD_TYPE=Debug

install:
  # Installing CMake 3.2.1
  - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -xzf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1
  - cmake .
  - make
  - cd ..
  - rm -rf cmake-3.2.1.tar.gz

before_script:
  - cmake-3.2.1/bin/cmake --version
  - mkdir build
  - cd build

script:
  - ../cmake-3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_PRECALCULATIONS=$ENABLE_PRECALCULATIONS -DENABLE_SIMD=$ENABLE_SIMD ../src/
  - make selftests_gost
  - ./libgost15/tests/selftests_gost
